## ======================================================================
## Pipeline for diskquota
## ======================================================================

groups:
- name: GPDB6
  jobs:
    - release_centos6
    - release_centos7
    - release_ubuntu18
    - diskquota_centos6_test_release
    - diskquota_centos7_test_release
    - diskquota_ubuntu18_test_release
    - diskquota_centos7_extension_upgrade_1.0_2.0

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:

# Image Resources

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

- name: centos-gpdb-dev-7
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '7-gcc6.2-llvm3.7'

- name: ubuntu18-image-build
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-ubuntu18.04-build
    tag: latest
  
- name: ubuntu18-image-test
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-ubuntu18.04-test
    tag: latest
  

# Github Source Codes

- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    uri: {{gpdb-git-remote}}

- name: diskquota_src
  type: git
  source:
    branch: gpdb
    uri: https://github.com/greenplum-db/diskquota.git
    tag_filter: 1.*

# gpdb binary on gcs is located as different folder for different version
# use gcs_gpdb_binary_folder to specify them.
- name: bin_gpdb_centos6
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_centos6/bin_gpdb.tar.gz

- name: bin_gpdb_centos7
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_centos7/bin_gpdb.tar.gz

- name: bin_gpdb_ubuntu18
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_ubuntu18.04/bin_gpdb.tar.gz

- name: bin_diskquota_centos7
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: diskquota/released/gpdb6/diskquota-(.*).tar.gz

- name: bin_diskquota_centos6
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: diskquota/released/gpdb6/diskquota-(.*).tar.gz

- name: bin_diskquota_ubuntu18
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: diskquota/released/gpdb6/diskquota-(.*).tar.gz

- name: bin_diskquota_centos7_1.0
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: diskquota/released/gpdb6/diskquota-(1.*)-rhel7_x86_64.tar.gz
## jobs
## ======================================================================

jobs:

- name: release_centos7
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: diskquota_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
    - get: gpdb_src
  - aggregate:
    - task: build_diskquota
      file: diskquota_src/concourse/tasks/build_diskquota.yml
      image: centos-gpdb-dev-7
  - aggregate:
    - task: test_diskquota
      file: diskquota_src/concourse/tasks/test_diskquota.yml
      image: centos-gpdb-dev-7
      input_mapping:
        bin_diskquota: diskquota_artifacts
      params:
        DISKQUOTA_OS: rhel7
  - aggregate:
    - put: bin_diskquota_centos7
      params:
        file: diskquota_artifacts/diskquota*.tar.gz

- name: release_centos6
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: diskquota_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos6
    - get: gpdb_src
  - aggregate:
    - task: build_diskquota
      file: diskquota_src/concourse/tasks/build_diskquota.yml
      image: centos-gpdb-dev-6
  - aggregate:
    - task: test_diskquota
      file: diskquota_src/concourse/tasks/test_diskquota.yml
      image: centos-gpdb-dev-6
      input_mapping:
        bin_diskquota: diskquota_artifacts
      params:
        DISKQUOTA_OS: rhel6
  - aggregate:
    - put: bin_diskquota_centos6
      params:
        file: diskquota_artifacts/diskquota*.tar.gz

- name: release_ubuntu18
  max_in_flight: 3
  plan:
  - aggregate:
    - get: ubuntu18-image-build
    - get: ubuntu18-image-test
    - get: diskquota_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu18
    - get: gpdb_src
  - aggregate:
    - task: build_diskquota
      file: diskquota_src/concourse/tasks/build_diskquota.yml
      image: ubuntu18-image-build
  - aggregate:
    - task: test_diskquota
      file: diskquota_src/concourse/tasks/test_diskquota.yml
      image: ubuntu18-image-test
      input_mapping:
        bin_diskquota: diskquota_artifacts
      params:
        DISKQUOTA_OS: ubuntu18.04
  - aggregate:
    - put: bin_diskquota_ubuntu18
      params:
        file: diskquota_artifacts/diskquota*.tar.gz

- name: diskquota_centos6_test_release
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: diskquota_src
    - get: bin_diskquota
      resource: bin_diskquota_centos6
    - get: bin_gpdb
      resource: bin_gpdb_centos6
      trigger: true
    - get: gpdb_src
  - task: test_diskquota
    file: diskquota_src/concourse/tasks/test_diskquota.yml
    image: centos-gpdb-dev-6

- name: diskquota_centos7_test_release
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: diskquota_src
    - get: bin_diskquota
      resource: bin_diskquota_centos7
    - get: bin_gpdb
      resource: bin_gpdb_centos7
      trigger: true
    - get: gpdb_src
  - task: test_diskquota
    file: diskquota_src/concourse/tasks/test_diskquota.yml
    image: centos-gpdb-dev-7

- name: diskquota_ubuntu18_test_release
  max_in_flight: 3
  plan:
  - aggregate:
    - get: ubuntu18-image-test
    - get: diskquota_src
    - get: bin_diskquota
      resource: bin_diskquota_ubuntu18
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu18
      trigger: true
    - get: gpdb_src
  - task: test_diskquota
    file: diskquota_src/concourse/tasks/test_diskquota.yml
    image: ubuntu18-image-test

- name: diskquota_centos7_extension_upgrade_1.0_2.0
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: bin_diskquota_old
      resource: bin_diskquota_centos7_1.0
    - get: bin_diskquota_new
      passed:
      - release_centos7
      resource: bin_diskquota_centos7
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
    - get: gpdb_src
    - get: diskquota_src
  - task: upgrade_extension
    file: diskquota_src/concourse/tasks/upgrade_extension.yml
    image: centos-gpdb-dev-7
    params:
      DISKQUOTA_OS: rhel7
      OLD_VERSION: "1.0"
      NEW_VERSION: "2.0"
